# Generated by Django 3.2.3 on 2021-05-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
            options={
                'unique_together': {('hour', 'minute')},
            },
        ),
    ]
